import type { VolcengineVoiceOption } from "@/lib/audio-generation";

// Generated from https://www.volcengine.com/docs/6561/1257544 (DocumentID 1257544).
// Keep this as data only; audio-generation.ts re-exports it for existing callers.
export const VOLCENGINE_VOICE_OPTIONS = [
    { value: "zh_female_vv_uranus_bigtts", label: "Vivi 2.0", gender: "female", age: "adult", tone: "通用场景 / 语种：中文、日文、印尼、墨西哥西班牙语", tags: ["通用场景","语种：中文、日文、印尼、墨西哥西班牙语"] },
    { value: "zh_female_xiaohe_uranus_bigtts", label: "小何 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_m191_uranus_bigtts", label: "云舟 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_taocheng_uranus_bigtts", label: "小天 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_liufei_uranus_bigtts", label: "刘飞 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_sophie_uranus_bigtts", label: "魅力苏菲 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_qingxinnvsheng_uranus_bigtts", label: "清新女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_cancan_uranus_bigtts", label: "知性灿灿 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循"] },
    { value: "zh_female_sajiaoxuemei_uranus_bigtts", label: "撒娇学妹 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循"] },
    { value: "zh_female_tianmeixiaoyuan_uranus_bigtts", label: "甜美小源 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_tianmeitaozi_uranus_bigtts", label: "甜美桃子 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_shuangkuaisisi_uranus_bigtts", label: "爽快思思 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_peiqi_uranus_bigtts", label: "佩奇猪 2.0", gender: "female", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_linjianvhai_uranus_bigtts", label: "邻家女孩 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_shaonianzixin_uranus_bigtts", label: "少年梓辛 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_sunwukong_uranus_bigtts", label: "猴哥 2.0", gender: "male", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "zh_female_yingyujiaoxue_uranus_bigtts", label: "Tina老师 2.0", gender: "female", age: "young", tone: "教育场景 / 中文、英式英语 / 指令遵循", tags: ["教育场景","中文、英式英语","指令遵循"] },
    { value: "zh_female_kefunvsheng_uranus_bigtts", label: "暖阳女声 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文 / 指令遵循", tags: ["客服场景","中文","指令遵循"] },
    { value: "zh_female_xiaoxue_uranus_bigtts", label: "儿童绘本 2.0", gender: "female", age: "young", tone: "有声阅读 / 中文 / 指令遵循", tags: ["有声阅读","中文","指令遵循"] },
    { value: "zh_male_dayi_uranus_bigtts", label: "大壹 2.0", gender: "male", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "zh_female_mizai_uranus_bigtts", label: "黑猫侦探社咪仔 2.0", gender: "female", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "zh_female_jitangnv_uranus_bigtts", label: "鸡汤女 2.0", gender: "female", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "zh_female_meilinvyou_uranus_bigtts", label: "魅力女友 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_liuchangnv_uranus_bigtts", label: "流畅女声 2.0", gender: "female", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "zh_male_ruyayichen_uranus_bigtts", label: "儒雅逸辰 2.0", gender: "male", age: "adult", tone: "视频配音 / 中文 / 指令遵循", tags: ["视频配音","中文","指令遵循"] },
    { value: "en_male_tim_uranus_bigtts", label: "Tim", gender: "male", age: "adult", tone: "多语种 / 美式英语 / 指令遵循", tags: ["多语种","美式英语","指令遵循"] },
    { value: "en_female_dacey_uranus_bigtts", label: "Dacey", gender: "female", age: "adult", tone: "多语种 / 美式英语 / 指令遵循", tags: ["多语种","美式英语","指令遵循"] },
    { value: "en_female_stokie_uranus_bigtts", label: "Stokie", gender: "female", age: "adult", tone: "多语种 / 美式英语 / 指令遵循", tags: ["多语种","美式英语","指令遵循"] },
    { value: "zh_female_wenroumama_uranus_bigtts", label: "温柔妈妈 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_jieshuoxiaoming_uranus_bigtts", label: "解说小明 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_tvbnv_uranus_bigtts", label: "TVB女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_yizhipiannan_uranus_bigtts", label: "译制片男 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_qiaopinv_uranus_bigtts", label: "俏皮女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_zhishuaiyingzi_uranus_bigtts", label: "直率英子 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_male_linjiananhai_uranus_bigtts", label: "邻家男孩 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_silang_uranus_bigtts", label: "四郎 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_male_ruyaqingnian_uranus_bigtts", label: "儒雅青年 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","番茄小说同款","豆包同款","剪映同款"] },
    { value: "zh_male_qingcang_uranus_bigtts", label: "擎苍 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","番茄小说同款","豆包同款","抖音同款"] },
    { value: "zh_male_xionger_uranus_bigtts", label: "熊二 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_yingtaowanzi_uranus_bigtts", label: "樱桃丸子 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_male_wennuanahu_uranus_bigtts", label: "温暖阿虎 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_naiqimengwa_uranus_bigtts", label: "奶气萌娃 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","剪映同款","豆包同款"] },
    { value: "zh_female_popo_uranus_bigtts", label: "婆婆 2.0", gender: "female", age: "old", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_gaolengyujie_uranus_bigtts", label: "高冷御姐 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_aojiaobazong_uranus_bigtts", label: "傲娇霸总 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_lanyinmianbao_uranus_bigtts", label: "懒音绵宝 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循"] },
    { value: "zh_male_fanjuanqingnian_uranus_bigtts", label: "反卷青年 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_wenroushunv_uranus_bigtts", label: "温柔淑女 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","番茄小说同款","豆包同款","剪映同款"] },
    { value: "zh_female_gufengshaoyu_uranus_bigtts", label: "古风少御 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循"] },
    { value: "zh_male_huolixiaoge_uranus_bigtts", label: "活力小哥 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_baqiqingshu_uranus_bigtts", label: "霸气青叔 2.0", gender: "male", age: "adult", tone: "有声阅读 / 中文 / 指令遵循", tags: ["有声阅读","中文","指令遵循","番茄小说同款","豆包同款","剪映同款"] },
    { value: "zh_male_xuanyijieshuo_uranus_bigtts", label: "悬疑解说 2.0", gender: "male", age: "young", tone: "有声阅读 / 中文 / 指令遵循", tags: ["有声阅读","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_mengyatou_uranus_bigtts", label: "萌丫头 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_tiexinnvsheng_uranus_bigtts", label: "贴心女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_jitangmei_uranus_bigtts", label: "鸡汤妹妹 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","豆包同款"] },
    { value: "zh_male_cixingjieshuonan_uranus_bigtts", label: "磁性解说男声 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_male_liangsangmengzai_uranus_bigtts", label: "亮嗓萌仔 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_kailangjiejie_uranus_bigtts", label: "开朗姐姐 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_gaolengchenwen_uranus_bigtts", label: "高冷沉稳 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","猫箱同款"] },
    { value: "zh_male_shenyeboke_uranus_bigtts", label: "深夜播客 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_lubanqihao_uranus_bigtts", label: "鲁班七号 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_jiaochuannv_uranus_bigtts", label: "娇喘女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_female_linxiao_uranus_bigtts", label: "林潇 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_lingling_uranus_bigtts", label: "玲玲姐姐 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_female_chunribu_uranus_bigtts", label: "春日部姐姐 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款","剪映同款"] },
    { value: "zh_male_tangseng_uranus_bigtts", label: "唐僧 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","豆包同款"] },
    { value: "zh_male_zhuangzhou_uranus_bigtts", label: "庄周 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_male_kailangdidi_uranus_bigtts", label: "开朗弟弟 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_male_zhubajie_uranus_bigtts", label: "猪八戒 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","豆包同款","剪映同款"] },
    { value: "zh_female_ganmaodianyin_uranus_bigtts", label: "感冒电音姐姐 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_female_chanmeinv_uranus_bigtts", label: "谄媚女声 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_female_nvleishen_uranus_bigtts", label: "女雷神 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","剪映同款","豆包同款"] },
    { value: "zh_female_qinqienv_uranus_bigtts", label: "亲切女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_male_kuailexiaodong_uranus_bigtts", label: "快乐小东 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_male_kailangxuezhang_uranus_bigtts", label: "开朗学长 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_male_youyoujunzi_uranus_bigtts", label: "悠悠君子 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_female_wenjingmaomao_uranus_bigtts", label: "文静毛毛 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_female_zhixingnv_uranus_bigtts", label: "知性女声 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_qingshuangnanda_uranus_bigtts", label: "清爽男大 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","豆包同款"] },
    { value: "zh_male_yuanboxiaoshu_uranus_bigtts", label: "渊博小叔 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_yangguangqingnian_uranus_bigtts", label: "阳光青年 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_qingchezizi_uranus_bigtts", label: "清澈梓梓 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_tianmeiyueyue_uranus_bigtts", label: "甜美悦悦 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_xinlingjitang_uranus_bigtts", label: "心灵鸡汤 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_wenrouxiaoge_uranus_bigtts", label: "温柔小哥 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_roumeinvyou_uranus_bigtts", label: "柔美女友 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_dongfanghaoran_uranus_bigtts", label: "东方浩然 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_wenrouxiaoya_uranus_bigtts", label: "温柔小雅 2.0", gender: "female", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_male_tiancaitongsheng_uranus_bigtts", label: "天才童声 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循"] },
    { value: "zh_female_wuzetian_uranus_bigtts", label: "武则天 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","剪映同款"] },
    { value: "zh_female_gujie_uranus_bigtts", label: "顾姐 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文 / 指令遵循", tags: ["角色扮演","中文","指令遵循","抖音同款","剪映同款"] },
    { value: "zh_male_guanggaojieshuo_uranus_bigtts", label: "广告解说 2.0", gender: "male", age: "young", tone: "通用场景 / 中文 / 指令遵循", tags: ["通用场景","中文","指令遵循","剪映同款"] },
    { value: "zh_female_shaoergushi_uranus_bigtts", label: "少儿故事 2.0", gender: "female", age: "young", tone: "有声阅读 / 中文 / 指令遵循", tags: ["有声阅读","中文","指令遵循"] },
    { value: "ICL_uranus_en_female_charlie_tob", label: "Charlie 2.0", gender: "female", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_ethan_tob", label: "Ethan 2.0", gender: "male", age: "adult", tone: "多语种 / 澳洲英语", tags: ["多语种","澳洲英语"] },
    { value: "ICL_uranus_en_male_alastor_tob", label: "Alastor 2.0", gender: "male", age: "adult", tone: "多语种 / 英式英语", tags: ["多语种","英式英语"] },
    { value: "ICL_uranus_en_male_chucky_tob", label: "Chucky 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_noah_tob", label: "Noah 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_jigsaw_tob", label: "Jigsaw 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_clown_man_tob", label: "Clown Man 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_cartoon_chef_tob", label: "Cartoon Chef 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_frosty_man_tob", label: "Frosty Man 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语","豆包同款"] },
    { value: "ICL_uranus_en_male_the_grinch_tob", label: "The Grinch 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语","豆包同款"] },
    { value: "ICL_uranus_en_male_kevin_mccallister_tob", label: "Kevin McCallister 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语","豆包同款"] },
    { value: "ICL_uranus_en_male_michael_tob", label: "Michael 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语","豆包同款"] },
    { value: "ICL_uranus_en_male_big_boogie_tob", label: "Big Boogie 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语","豆包同款"] },
    { value: "ICL_uranus_en_male_xavier_tob", label: "Xavier 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_en_male_zayne_tob", label: "Zayne 2.0", gender: "male", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "ICL_uranus_zh_female_aojiaonvyou_tob", label: "傲娇女友 2.0", gender: "female", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_aomanjiaosheng_tob", label: "傲慢娇声 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_xiemeinvwang_tob", label: "邪魅女王 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_bingjiaojiejie_tob", label: "病娇姐姐 2.0", gender: "female", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_bingjiaomengmei_tob", label: "病娇萌妹 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_bingruoshaonv_tob", label: "病弱少女 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_chengshuwenrou_tob", label: "成熟温柔 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_chengshujiejie_tob", label: "成熟姐姐 2.0", gender: "female", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_chunzhenshaonv_tob", label: "纯真少女 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_female_chunchenvsheng_tob", label: "纯澈女生 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_wumeikeren_tob", label: "妩媚可人 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_guaiqiaokeer_tob", label: "乖巧可儿 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_heainainai_tob", label: "和蔼奶奶 2.0", gender: "female", age: "old", tone: "视频配音 / 中文", tags: ["视频配音","中文"] },
    { value: "ICL_uranus_zh_female_huopodiaoman_tob", label: "活泼刁蛮 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_huoponvhai_tob", label: "活泼女孩 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_jiaohannvwang_tob", label: "娇憨女王 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_jiaoruoluoli_tob", label: "娇弱萝莉 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_jiaxiaozi_tob", label: "假小子 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_jinglingxiangdao_tob", label: "精灵向导 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_female_kailangtingting_tob", label: "开朗婷婷 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_kaixinxiaohong_tob", label: "开心小鸿 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_keainvsheng_tob", label: "可爱女生 2.0", gender: "female", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_lingdongxinxin_tob", label: "灵动欣欣 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_linjuayi_tob", label: "邻居阿姨 2.0", gender: "female", age: "adult", tone: "视频配音 / 中文", tags: ["视频配音","中文"] },
    { value: "ICL_uranus_zh_female_tianmeijiaoqiao_tob", label: "甜美娇俏 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_qinglenggaoya_tob", label: "清冷高雅 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_lixingyuanzi_tob", label: "理性圆子 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_xingganmeihuo_tob", label: "性感魅惑 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_nuanxinqianqian_tob", label: "暖心茜茜 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_nuanxinxuejie_tob", label: "暖心学姐 2.0", gender: "female", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_qingtianmeimei_tob", label: "清甜莓莓 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_qingtiantaotao_tob", label: "清甜桃桃 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_qingxixiaoxue_tob", label: "清晰小雪 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_qingxinshaonv_tob", label: "倾心少女 2.0", gender: "female", age: "young", tone: "视频配音 / 中文", tags: ["视频配音","中文"] },
    { value: "ICL_uranus_zh_female_rouguhunshi_tob", label: "柔骨魂师 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_ruanmengtangtang_tob", label: "软萌糖糖 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_ruanmengtuanzi_tob", label: "软萌团子 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_tianmeihuopo_tob", label: "甜美活泼 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_tianmeixiaoju_tob", label: "甜美小橘 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_tianmeixiaoyu_tob", label: "甜美小雨 2.0", gender: "female", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_tiaopigongzhu_tob", label: "调皮公主 2.0", gender: "female", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_tiexinnvyou_tob", label: "贴心女友 2.0", gender: "female", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_wenrounvshen_tob", label: "温柔女神 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文","豆包同款"] },
    { value: "ICL_uranus_zh_female_wenrouwenya_tob", label: "温柔文雅 2.0", gender: "female", age: "adult", tone: "通用场景,S2S-SC / 中文", tags: ["通用场景","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_female_zhixinjiejie_tob", label: "知心姐姐 2.0", gender: "female", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_wumeiyujie_tob", label: "妩媚御姐 2.0", gender: "female", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款"] },
    { value: "ICL_uranus_zh_female_yuanqitianmei_tob", label: "元气甜妹 2.0", gender: "female", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_xiemeiyujie_tob", label: "邪魅御姐 2.0", gender: "female", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_xingganyujie_tob", label: "性感御姐 2.0", gender: "female", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_female_xiuliqianqian_tob", label: "秀丽倩倩 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_tiexinguimi_tob", label: "贴心闺蜜 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_tiexinmeimei_tob", label: "贴心妹妹 2.0", gender: "female", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_wenroubaiyueguang_tob", label: "温柔白月光 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_chuliannvyou_tob", label: "初恋女友 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_female_zhixingwenwan_tob", label: "知性温婉 2.0", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_aoqilingren_tob", label: "傲气凌人 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_anrenqinzhu_tob", label: "黯刃秦主 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_aojiaogongzi_tob", label: "傲娇公子 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_aojiaojingying_tob", label: "傲娇精英 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_aomanqingnian_tob", label: "傲慢青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_aomanshaoye_tob", label: "傲慢少爷 2.0", gender: "male", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_zhenbiandiyu_tob", label: "枕边低语 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","抖音同款"] },
    { value: "ICL_uranus_zh_male_badaoshaoye_tob", label: "霸道少爷 2.0", gender: "male", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_badaozongcai_tob", label: "霸道总裁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_bingjiaobailian_tob", label: "病娇白莲 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_bingjiaodidi_tob", label: "病娇弟弟 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_bingjiaogege_tob", label: "病娇哥哥 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_bingjiaonanyou_tob", label: "病娇男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_bingjiaoshaonian_tob", label: "病娇少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_bingruogongzi_tob", label: "病弱公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_bingruoshaonian_tob", label: "病弱少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_bujiqingnian_tob", label: "不羁青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_chunhoudiyin_tob", label: "醇厚低音 2.0", gender: "male", age: "adult", tone: "视频配音 / 中文", tags: ["视频配音","中文"] },
    { value: "ICL_uranus_zh_male_paoxiaoxiaoge_tob", label: "咆哮小哥 2.0", gender: "male", age: "young", tone: "视频配音 / 中文", tags: ["视频配音","中文"] },
    { value: "ICL_uranus_zh_male_yangyang_tob", label: "炀炀 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_male_chanruoshaoye_tob", label: "孱弱少爷 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_chengshuzongcai_tob", label: "成熟总裁 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_chenwenmingzai_tob", label: "沉稳明仔 2.0", gender: "male", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_qingyisugan_tob", label: "清逸苏感 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_chunzhenxuedi_tob", label: "纯真学弟 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_cixingnansang_tob", label: "磁性男嗓 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_cujingnansheng_tob", label: "醋精男生 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_cujingnanyou_tob", label: "醋精男友 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_diyinchenyu_tob", label: "低音沉郁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_fengfashaonian_tob", label: "风发少年 2.0", gender: "male", age: "young", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文"] },
    { value: "ICL_uranus_zh_male_ruyagongzi_tob", label: "儒雅公子 2.0", gender: "male", age: "adult", tone: "有声阅读 / 中文", tags: ["有声阅读","中文"] },
    { value: "ICL_uranus_zh_male_fuheigongzi_tob", label: "腹黑公子 2.0", gender: "male", age: "adult", tone: "角色扮演,S2S-SC / 中文", tags: ["角色扮演","S2S-SC","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_ganjingshaonian_tob", label: "干净少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_gaolengzongcai_tob", label: "高冷总裁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_guaogongzi_tob", label: "孤傲公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_gugaogongzi_tob", label: "孤高公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_guiyishenmi_tob", label: "诡异神秘 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_guzhibingjiao_tob", label: "固执病娇 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_hanhoudunshi_tob", label: "憨厚敦实 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_huoliqingnian_tob", label: "活力青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_huoponanyou_tob", label: "活泼男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_huoposhuanglang_tob", label: "活泼爽朗 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_huzishushu_tob", label: "胡子叔叔 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_jijiazhineng_tob", label: "机甲智能 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_jingyingqingnian_tob", label: "精英青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_junyigongzi_tob", label: "俊逸公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_kailangqingkuai_tob", label: "开朗轻快 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_kailangqingnian_tob", label: "开朗青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lanyincaohunshi_tob", label: "蓝银草魂师 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_lengaozongcai_tob", label: "冷傲总裁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lengdanshuli_tob", label: "冷淡疏离 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_lengjungaozhi_tob", label: "冷峻高智 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lengjunshangsi_tob", label: "冷峻上司 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_lengkugege_tob", label: "冷酷哥哥 2.0", gender: "male", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_lenglianxiongzhang_tob", label: "冷脸兄长 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lenglianxueba_tob", label: "冷脸学霸 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lengmonanyou_tob", label: "冷漠男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lengmoxiongzhang_tob", label: "冷漠兄长 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_lingyunqingnian_tob", label: "凌云青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_qinglengjingui_tob", label: "清冷矜贵 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_lvchaxiaoge_tob", label: "绿茶小哥 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_mengdongqingnian_tob", label: "懵懂青年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_menyoupingxiaoge_tob", label: "闷油瓶小哥 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_xiaozhangxiaoge_tob", label: "嚣张小哥 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_nianrennanyou_tob", label: "粘人男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_neiliancaijun_tob", label: "内敛才俊 2.0", gender: "male", age: "adult", tone: "有声阅读 / 中文", tags: ["有声阅读","中文"] },
    { value: "ICL_uranus_zh_male_nuanxintitie_tob", label: "暖心体贴 2.0", gender: "male", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_pianpiangongzi_tob", label: "翩翩公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_chenwenyouya_tob", label: "沉稳优雅 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_qingsexiaosheng_tob", label: "青涩小生 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_qingseqingnian_tob", label: "青涩青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_qingshuangshaonian_tob", label: "清爽少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_qingxinbobo_tob", label: "清新波波 2.0", gender: "male", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_qinqieqingnian_tob", label: "亲切青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_qinqiexiaozhuo_tob", label: "亲切小卓 2.0", gender: "male", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_qinglangwenrun_tob", label: "清朗温润 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_rexueshaonian_tob", label: "热血少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_ruyacaijun_tob", label: "儒雅才俊 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_ruyajunzi_tob", label: "儒雅君子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_ruyazongcai_tob", label: "儒雅总裁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_sajiaonansheng_tob", label: "撒娇男生 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_sajiaonanyou_tob", label: "撒娇男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_sajiaonianren_tob", label: "撒娇粘人 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_satuoqingnian_tob", label: "洒脱青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_shaonianjiangjun_tob", label: "少年将军 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_shenchenzongcai_tob", label: "深沉总裁 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_jilingxiaohuo_tob", label: "机灵小伙 2.0", gender: "male", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "ICL_uranus_zh_male_shenmifashi_tob", label: "神秘法师 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_shuaizhenxiaohuo_tob", label: "率真小伙 2.0", gender: "male", age: "young", tone: "通用场景 / 中文", tags: ["通用场景","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_shuanglangxiaoyang_tob", label: "爽朗小阳 2.0", gender: "male", age: "young", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_dichenqianquan_tob", label: "低沉缱绻 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_siwenqingnian_tob", label: "斯文青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_tianxinanyou_tob", label: "甜系男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_tiexinnanyou_tob", label: "贴心男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_wenrounantongzhuo_tob", label: "温柔男同桌 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_wenrounanyou_tob", label: "温柔男友 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_wenrouxuezhang_tob", label: "温柔学长 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_wenrunxuezhe_tob", label: "温润学者 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_wenshunshaonian_tob", label: "温顺少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_guayanxiaoge_tob", label: "寡言小哥 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_xiaohouye_tob", label: "小侯爷 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_naiqixiaosheng_tob", label: "奶气小生 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款"] },
    { value: "ICL_uranus_zh_male_xiaosasuixing_tob", label: "潇洒随性 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_wenrouneilian_tob", label: "温柔内敛 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_xuebanantongzhuo_tob", label: "学霸男同桌 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_xuebatongzhuo_tob", label: "学霸同桌 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_yangguangyangyang_tob", label: "阳光洋洋 2.0", gender: "male", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_wennuanshaonian_tob", label: "温暖少年 2.0", gender: "male", age: "young", tone: "有声阅读 / 中文", tags: ["有声阅读","中文"] },
    { value: "ICL_uranus_zh_male_yiqishaonian_tob", label: "意气少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_younidashu_tob", label: "油腻大叔 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_youmodaye_tob", label: "幽默大爷 2.0", gender: "male", age: "old", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_youmoshushu_tob", label: "幽默叔叔 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_youroubangzhu_tob", label: "优柔帮主 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_yourougongzi_tob", label: "优柔公子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","豆包同款","猫箱同款"] },
    { value: "ICL_uranus_zh_male_yuanqishaonian_tob", label: "元气少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zhangjianjunzi_tob", label: "仗剑君子 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zhangjianxiake_tob", label: "仗剑侠客 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zhengzhiqingnian_tob", label: "正直青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","猫箱同款"] },
    { value: "ICL_uranus_zh_male_zhishuaiqingnian_tob", label: "直率青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zhongerqingnian_tob", label: "中二青年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zifuqingnian_tob", label: "自负青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_zixinqingnian_tob", label: "自信青年 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_tiancaitongzhuo_tob", label: "天才同桌 2.0", gender: "male", age: "adult", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_male_qingxinmumu_tob", label: "清新沐沐 2.0", gender: "male", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_wenwanshanshan_tob", label: "温婉珊珊 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_female_reqingaina_tob", label: "热情艾娜 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ICL_uranus_zh_male_shuanglangshaonian_tob", label: "爽朗少年 2.0", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文"] },
    { value: "ICL_uranus_zh_female_qingyingduoduo_tob", label: "轻盈朵朵 2.0", gender: "female", age: "adult", tone: "客服场景 / 中文", tags: ["客服场景","中文"] },
    { value: "ar_female_dina_uranus_bigtts", label: "Dina", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,阿拉伯语 / 阿拉伯语 / QA", tags: ["通用场景","视频配音","多语种","阿拉伯语","QA","情感变化、指令遵循"] },
    { value: "ar_female_fatma_uranus_bigtts", label: "Fatma", gender: "female", age: "adult", tone: "趣味口音,多语种,阿拉伯语 / 阿拉伯语 / QA", tags: ["趣味口音","多语种","阿拉伯语","QA","情感变化、指令遵循"] },
    { value: "ar_male_youssef_uranus_bigtts", label: "Youssef", gender: "male", age: "adult", tone: "通用场景,有声阅读,多语种,阿拉伯语 / 阿拉伯语 / QA", tags: ["通用场景","有声阅读","多语种","阿拉伯语","QA","情感变化、指令遵循"] },
    { value: "de_female_bv081_uranus_bigtts", label: "Stella", gender: "female", age: "adult", tone: "教学场景, 客服场景,多语种,德语 / 德语 / QA", tags: ["教学场景","客服场景","多语种","德语","QA","情感变化、指令遵循"] },
    { value: "de_male_sven_uranus_bigtts", label: "Sven", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,德语 / 德语 / Context", tags: ["通用场景","教学场景","多语种","德语","Context","情感变化、上下文遵循"] },
    { value: "imitation_uranus_bigtts", label: "imitation_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_alberto_uranus_bigtts", label: "Alberto", gender: "male", age: "adult", tone: "通用场景, 教学场景,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","教学场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_alex_uranus_bigtts", label: "Alex", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_allison_uranus_bigtts", label: "Allison", gender: "female", age: "adult", tone: "视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "british_uranus_bigtts", label: "british_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "informative_uranus_bigtts", label: "informative_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "jones_uranus_bigtts", label: "jones_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_bill_jones_corey_uranus_bigtts", label: "Bill", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / Context", tags: ["通用场景","视频配音","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_male_brad_pitt_p1_uranus_bigtts", label: "Brad_Pitt", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_brittney_uranus_bigtts", label: "Brittney", gender: "female", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_brittney_pimintel_uranus_bigtts", label: "Zoe", gender: "female", age: "adult", tone: "有声阅读, 客服场景,美式英语,多语种 / 美式英语 / Context", tags: ["有声阅读","客服场景","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_male_bruce_uranus_bigtts", label: "Adrian", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_chandler_p1_uranus_bigtts", label: "Leo", gender: "male", age: "adult", tone: "趣味口音,美式英语,多语种 / 美式英语 / QA", tags: ["趣味口音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "bob_uranus_bigtts", label: "bob_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_cowboy_john_b_uranus_bigtts", label: "John", gender: "male", age: "adult", tone: "趣味口音, 角色扮演,美式英语,多语种 / 美式英语 / Context", tags: ["趣味口音","角色扮演","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_male_david_uranus_bigtts", label: "David", gender: "male", age: "adult", tone: "通用场景,有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "voice_uranus_bigtts", label: "voice_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_diyuwenrounan_uranus_bigtts", label: "Julian", gender: "male", age: "adult", tone: "有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "oxley_uranus_bigtts", label: "oxley_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "christmas_uranus_bigtts", label: "christmas_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "jenny_uranus_bigtts", label: "jenny_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "martinez_uranus_bigtts", label: "martinez_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_godfather_uranus_bigtts", label: "Godfather", gender: "male", age: "adult", tone: "有声阅读, 角色扮演,美式英语,多语种 / 美式英语 / QA", tags: ["有声阅读","角色扮演","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_gollum_uranus_bigtts", label: "Gollum", gender: "male", age: "adult", tone: "角色扮演,美式英语,多语种 / 美式英语 / QA", tags: ["角色扮演","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_hades_uranus_bigtts", label: "Beau", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_hayley_uranus_bigtts", label: "Hayley", gender: "female", age: "adult", tone: "教学场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["教学场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_jamie_uranus_bigtts", label: "Jamie", gender: "male", age: "adult", tone: "通用场景, 教学场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","教学场景","视频配音","美式英语","多语种","QA"] },
    { value: "en_female_jane_uranus_bigtts", label: "Jane", gender: "female", age: "adult", tone: "视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_jenny_uranus_bigtts", label: "Jenny", gender: "female", age: "adult", tone: "通用场景, 客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_jidongchuanjiaoshi_uranus_bigtts", label: "Blaze", gender: "male", age: "adult", tone: "趣味口音, 角色扮演,美式英语,多语种 / 美式英语 / QA", tags: ["趣味口音","角色扮演","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_jimmy_uranus_bigtts", label: "Jimmy", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_joanne_uranus_bigtts", label: "Joanne", gender: "female", age: "adult", tone: "通用场景,有声阅读, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","有声阅读","视频配音","美式英语","多语种","QA"] },
    { value: "en_male_joker_uranus_bigtts", label: "Joker", gender: "male", age: "adult", tone: "趣味口音, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["趣味口音","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_josh_uranus_bigtts", label: "Josh", gender: "male", age: "adult", tone: "视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_josh_coery_uranus_bigtts", label: "Josiah", gender: "male", age: "adult", tone: "教学场景, 视频配音,美式英语,多语种 / 美式英语 / Context", tags: ["教学场景","视频配音","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_male_kevin_uranus_bigtts", label: "Kevin", gender: "male", age: "adult", tone: "教学场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["教学场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_knightley_uranus_bigtts", label: "Knightley", gender: "male", age: "adult", tone: "有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_lana_del_rey_kelley_d_p1_uranus_bigtts", label: "Lynn", gender: "female", age: "adult", tone: "角色扮演,美式英语,多语种 / 美式英语 / QA", tags: ["角色扮演","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_lana_del_rey_parky_s_p1_uranus_bigtts", label: "Ivy", gender: "female", age: "adult", tone: "客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_marcus_uranus_bigtts", label: "Marcus", gender: "male", age: "adult", tone: "通用场景,有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_mel_uranus_bigtts", label: "Mel", gender: "female", age: "adult", tone: "教学场景, 客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["教学场景","客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_michael_uranus_bigtts", label: "Hank", gender: "male", age: "adult", tone: "通用场景, 教学场景,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","教学场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "mouse_uranus_bigtts", label: "mouse_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_male_michael_kevin_uranus_bigtts", label: "Michael_Kevin", gender: "male", age: "adult", tone: "通用场景, 教学场景,美式英语,多语种 / 美式英语 / Context", tags: ["通用场景","教学场景","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "coach_uranus_bigtts", label: "coach_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_female_myra_uranus_bigtts", label: "Myra", gender: "female", age: "adult", tone: "教学场景,美式英语,多语种 / 美式英语 / QA", tags: ["教学场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_myra_cmb_uranus_bigtts", label: "Sunny", gender: "female", age: "adult", tone: "教学场景, 客服场景,美式英语,多语种 / 美式英语 / Context", tags: ["教学场景","客服场景","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_female_nadia_uranus_bigtts", label: "Blair", gender: "female", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_natasha_uranus_bigtts", label: "Natasha", gender: "female", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "female_uranus_bigtts", label: "female_uranus_bigtts", gender: "female", age: "adult", tone: "Official voice", tags: [] },
    { value: "en_female_rachel_p1_uranus_bigtts", label: "Rachel", gender: "female", age: "adult", tone: "趣味口音,美式英语,多语种 / 美式英语 / QA", tags: ["趣味口音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_ronald_uranus_bigtts", label: "Ronald", gender: "male", age: "adult", tone: "有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_russell_uranus_bigtts", label: "Russell", gender: "male", age: "adult", tone: "通用场景, 教学场景,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","教学场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_scarlet_p1_uranus_bigtts", label: "Scarlet", gender: "female", age: "adult", tone: "客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_sharron_uranus_bigtts", label: "Sharron", gender: "female", age: "adult", tone: "趣味口音,美式英语,多语种 / 美式英语 / QA", tags: ["趣味口音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_simba_p1_uranus_bigtts", label: "Simba", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_skye_uranus_bigtts", label: "Skye", gender: "female", age: "adult", tone: "通用场景,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_tom_hiddleston_p1_uranus_bigtts", label: "Tom", gender: "male", age: "adult", tone: "通用场景,有声阅读,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","有声阅读","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_valentino_uranus_bigtts", label: "Valentino", gender: "male", age: "adult", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_valentino_corey_uranus_bigtts", label: "Clark", gender: "male", age: "adult", tone: "视频配音,美式英语,多语种 / 美式英语 / Context", tags: ["视频配音","美式英语","多语种","Context","情感变化、上下文遵循"] },
    { value: "en_female_wenrouzhishijieshuonv_uranus_bigtts", label: "Megan", gender: "female", age: "young", tone: "客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_xinwenjieshuonv_uranus_bigtts", label: "Kayla", gender: "female", age: "young", tone: "角色扮演,美式英语,多语种 / 美式英语 / QA", tags: ["角色扮演","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_male_yangguangjieshuonan_uranus_bigtts", label: "Dylan", gender: "male", age: "young", tone: "通用场景, 视频配音,美式英语,多语种 / 美式英语 / QA", tags: ["通用场景","视频配音","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "en_female_zendaya_p1_uranus_bigtts", label: "Zendaya", gender: "female", age: "adult", tone: "教学场景, 客服场景,美式英语,多语种 / 美式英语 / QA", tags: ["教学场景","客服场景","美式英语","多语种","QA","情感变化、指令遵循"] },
    { value: "es_female_bv084_uranus_bigtts", label: "Gracie", gender: "female", age: "adult", tone: "通用场景, 客服场景,多语种,西班牙语 / 西班牙语 / QA", tags: ["通用场景","客服场景","多语种","西班牙语","QA","情感变化、指令遵循"] },
    { value: "es_male_dani_uranus_bigtts", label: "Dani", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,西班牙语 / 西班牙语 / QA", tags: ["有声阅读","视频配音","多语种","西班牙语","QA","情感变化、指令遵循"] },
    { value: "es_male_guillem_uranus_bigtts", label: "Guillem", gender: "male", age: "adult", tone: "有声阅读,多语种,西班牙语 / 西班牙语 / QA", tags: ["有声阅读","多语种","西班牙语","QA","情感变化、指令遵循"] },
    { value: "es_female_ht_mx_f6_uranus_bigtts", label: "Marisol", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,西班牙语 / 西班牙语 / QA", tags: ["通用场景","视频配音","多语种","西班牙语","QA","情感变化、指令遵循"] },
    { value: "fr_female_fr_bv078_uranus_bigtts", label: "Simone", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,法语 / 法语 / QA", tags: ["通用场景","视频配音","多语种","法语","QA","情感变化、指令遵循"] },
    { value: "fr_female_fr_f47_uranus_bigtts", label: "Camille", gender: "female", age: "adult", tone: "教学场景, 客服场景,多语种,法语 / 法语 / QA", tags: ["教学场景","客服场景","多语种","法语","QA","情感变化、指令遵循"] },
    { value: "fr_male_fr_m29_uranus_bigtts", label: "Maurice", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,法语 / 法语 / QA", tags: ["有声阅读","视频配音","多语种","法语","QA","情感变化、指令遵循"] },
    { value: "fr_male_usseau_uranus_bigtts", label: "Usseau", gender: "male", age: "adult", tone: "通用场景, 客服场景,多语种,法语 / 法语 / Context", tags: ["通用场景","客服场景","多语种","法语","Context","情感变化、上下文遵循"] },
    { value: "id_male_bv160_uranus_bigtts", label: "Rocco", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_male_bv160dialogue_uranus_bigtts", label: "Jude", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_male_bv160narration_uranus_bigtts", label: "Hugo", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["有声阅读","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_bv161_uranus_bigtts", label: "Clara", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_bv161dialogue_uranus_bigtts", label: "Sylvia", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_bv161narration_uranus_bigtts", label: "Celeste", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_bv164_uranus_bigtts", label: "Crew", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_male_bv164dialogue_uranus_bigtts", label: "Elian", gender: "male", age: "adult", tone: "视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_male_bv164narration_uranus_bigtts", label: "Ronan", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["有声阅读","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_f20_uranus_bigtts", label: "Chloe", gender: "female", age: "adult", tone: "视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_male_han_uranus_bigtts", label: "Han", gender: "male", age: "adult", tone: "通用场景,多语种,印尼语 / 印尼语 / Context", tags: ["通用场景","多语种","印尼语","Context","情感变化、指令遵循、上下文遵循"] },
    { value: "id_male_m08_uranus_bigtts", label: "Kyle", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","教学场景","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "id_female_phulia_uranus_bigtts", label: "Phulia", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,印尼语 / 印尼语 / QA", tags: ["通用场景","视频配音","多语种","印尼语","QA","情感变化、指令遵循"] },
    { value: "ja_female_bv024_uranus_bigtts", label: "Bonnie", gender: "female", age: "adult", tone: "通用场景, 教学场景,多语种,日语 / 日语 / QA", tags: ["通用场景","教学场景","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ja_female_bv520_uranus_bigtts", label: "Poppy", gender: "female", age: "adult", tone: "视频配音, 角色扮演,多语种,日语 / 日语 / QA", tags: ["视频配音","角色扮演","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ja_female_bv521_uranus_bigtts", label: "Aoi", gender: "female", age: "adult", tone: "趣味口音, 角色扮演,多语种,日语 / 日语 / QA", tags: ["趣味口音","角色扮演","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ja_female_bv522_uranus_bigtts", label: "Hana", gender: "female", age: "adult", tone: "通用场景, 教学场景, 客服场景,多语种,日语 / 日语 / QA", tags: ["通用场景","教学场景","客服场景","多语种","日语","QA"] },
    { value: "ja_female_bv523_uranus_bigtts", label: "Lily", gender: "female", age: "adult", tone: "趣味口音, 角色扮演,多语种,日语 / 日语 / QA", tags: ["趣味口音","角色扮演","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ja_male_bv524_uranus_bigtts", label: "Ken", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,日语 / 日语 / QA", tags: ["通用场景","视频配音","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ja_female_minimi_uranus_bigtts", label: "Minimi", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,日语 / 日语 / Context", tags: ["通用场景","视频配音","多语种","日语","Context","情感变化、上下文遵循"] },
    { value: "ja_female_shirou_uranus_bigtts", label: "Shirou", gender: "female", age: "adult", tone: "视频配音, 角色扮演,多语种,日语 / 日语 / QA", tags: ["视频配音","角色扮演","多语种","日语","QA","情感变化、指令遵循"] },
    { value: "ko_male_bv545_uranus_bigtts", label: "Jay", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,韩语 / 韩语 / QA", tags: ["通用场景","视频配音","多语种","韩语","QA","情感变化、指令遵循"] },
    { value: "ko_female_bv546_uranus_bigtts", label: "Momo", gender: "female", age: "adult", tone: "视频配音, 角色扮演,多语种,韩语 / 韩语 / QA", tags: ["视频配音","角色扮演","多语种","韩语","QA","情感变化、指令遵循"] },
    { value: "ko_male_m03_uranus_bigtts", label: "Minho", gender: "male", age: "adult", tone: "通用场景, 客服场景,多语种,韩语 / 韩语 / QA", tags: ["通用场景","客服场景","多语种","韩语","QA","情感变化、指令遵循"] },
    { value: "ko_male_shane_uranus_bigtts", label: "Shane", gender: "male", age: "adult", tone: "有声阅读, 教学场景, 视频配音,多语种,韩语 / 韩语 / Context", tags: ["有声阅读","教学场景","视频配音","多语种","韩语","Context"] },
    { value: "ms_male_ham_uranus_bigtts", label: "Ham", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,马来语 / 马来语 / QA", tags: ["通用场景","教学场景","多语种","马来语","QA","情感变化、指令遵循"] },
    { value: "ms_male_naim_uranus_bigtts", label: "Naim", gender: "male", age: "adult", tone: "通用场景, 客服场景,多语种,马来语 / 马来语 / QA", tags: ["通用场景","客服场景","多语种","马来语","QA","情感变化、指令遵循"] },
    { value: "mx_female_bv065_uranus_bigtts", label: "Irene", gender: "female", age: "adult", tone: "教学场景, 视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["教学场景","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_male_bv165dialogue_uranus_bigtts", label: "Diego", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["有声阅读","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_male_bv165narrator_uranus_bigtts", label: "Marcos", gender: "male", age: "adult", tone: "有声阅读,视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["有声阅读","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_female_bv166dialogue_uranus_bigtts", label: "Lucy", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["通用场景","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_female_bv166emotion_uranus_bigtts", label: "Rosa", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["通用场景","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_female_bv166narrator_uranus_bigtts", label: "Freya", gender: "female", age: "adult", tone: "有声阅读, 视频配音, 客服场景,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["有声阅读","视频配音","客服场景","多语种","墨西哥西语","QA"] },
    { value: "mx_male_felipe_uranus_bigtts", label: "Felipe", gender: "male", age: "adult", tone: "通用场景,有声阅读,多语种,墨西哥西语 / 墨西哥西语 / Context", tags: ["通用场景","有声阅读","多语种","墨西哥西语","Context","情感变化、上下文遵循"] },
    { value: "mx_male_ht_mx_m012_uranus_bigtts", label: "Derek", gender: "male", age: "adult", tone: "教学场景, 视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["教学场景","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_female_leslie_uranus_bigtts", label: "Leslie", gender: "female", age: "adult", tone: "通用场景, 客服场景,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["通用场景","客服场景","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "mx_male_marcelo_uranus_bigtts", label: "Marcelo", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,墨西哥西语 / 墨西哥西语 / QA", tags: ["通用场景","视频配音","多语种","墨西哥西语","QA","情感变化、指令遵循"] },
    { value: "pt_male_bv172_uranus_bigtts", label: "Sam", gender: "male", age: "adult", tone: "通用场景, 客服场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["通用场景","客服场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_male_bv172dialogue_uranus_bigtts", label: "Walter", gender: "male", age: "adult", tone: "视频配音,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["视频配音","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_male_bv172emotion_uranus_bigtts", label: "Vincent", gender: "male", age: "adult", tone: "教学场景, 视频配音,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["教学场景","视频配音","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_male_bv172narrator_uranus_bigtts", label: "Miles", gender: "male", age: "adult", tone: "有声阅读, 角色扮演,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["有声阅读","角色扮演","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_bv173_uranus_bigtts", label: "Diana", gender: "female", age: "adult", tone: "通用场景, 教学场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["通用场景","教学场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_bv173dialogue_uranus_bigtts", label: "Elena", gender: "female", age: "adult", tone: "视频配音, 客服场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["视频配音","客服场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_bv173emotion_uranus_bigtts", label: "Lola", gender: "female", age: "adult", tone: "通用场景, 教学场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["通用场景","教学场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_bv173narrator_uranus_bigtts", label: "Emma", gender: "female", age: "adult", tone: "视频配音, 客服场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["视频配音","客服场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_bv530_uranus_bigtts", label: "Sofia", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["通用场景","视频配音","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_male_bv531_uranus_bigtts", label: "Arthur", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["通用场景","教学场景","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_female_mari_uranus_bigtts", label: "Mari", gender: "female", age: "adult", tone: "教学场景, 视频配音,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["教学场景","视频配音","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "pt_male_martins_uranus_bigtts", label: "Toby", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / Context", tags: ["通用场景","教学场景","多语种","巴西葡萄牙语","Context","情感变化、上下文遵循"] },
    { value: "pt_male_rael_uranus_bigtts", label: "Rael", gender: "male", age: "adult", tone: "教学场景, 视频配音,多语种,巴西葡萄牙语 / 巴西葡萄牙语 / QA", tags: ["教学场景","视频配音","多语种","巴西葡萄牙语","QA","情感变化、指令遵循"] },
    { value: "ru_female_af07_uranus_bigtts", label: "Amelia", gender: "female", age: "adult", tone: "有声阅读,视频配音,多语种,俄语 / 俄语 / QA", tags: ["有声阅读","视频配音","多语种","俄语","QA","情感变化、指令遵循"] },
    { value: "ru_female_irinae_uranus_bigtts", label: "Irinae", gender: "female", age: "adult", tone: "有声阅读,视频配音,多语种,俄语 / 俄语 / QA", tags: ["有声阅读","视频配音","多语种","俄语","QA","情感变化、指令遵循"] },
    { value: "ru_male_pavel_uranus_bigtts", label: "Pavel", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,俄语 / 俄语 / QA", tags: ["通用场景","视频配音","多语种","俄语","QA","情感变化、指令遵循"] },
    { value: "ru_female_sophie_uranus_bigtts", label: "Ksenia", gender: "female", age: "adult", tone: "通用场景,多语种,俄语 / 俄语 / QA", tags: ["通用场景","多语种","俄语","QA","情感变化、指令遵循"] },
    { value: "ru_male_vlad_uranus_bigtts", label: "Silas", gender: "male", age: "adult", tone: "趣味口音,多语种,俄语 / 俄语 / QA", tags: ["趣味口音","多语种","俄语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_angry_uranus_bigtts", label: "Valeria", gender: "female", age: "adult", tone: "教学场景, 视频配音,多语种,泰语 / 泰语 / QA", tags: ["教学场景","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_fear_uranus_bigtts", label: "Iris", gender: "female", age: "adult", tone: "有声阅读,视频配音,多语种,泰语 / 泰语 / QA", tags: ["有声阅读","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_happy_uranus_bigtts", label: "Zara", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,泰语 / 泰语 / QA", tags: ["通用场景","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_hate_uranus_bigtts", label: "Valentina", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,泰语 / 泰语 / QA", tags: ["通用场景","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_neutral_uranus_bigtts", label: "Mildred", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,泰语 / 泰语 / QA", tags: ["通用场景","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_sad_uranus_bigtts", label: "Lydia", gender: "female", age: "adult", tone: "视频配音, 客服场景,多语种,泰语 / 泰语 / QA", tags: ["视频配音","客服场景","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "th_female_bv568_suprise_uranus_bigtts", label: "Phoebe", gender: "female", age: "adult", tone: "有声阅读,视频配音,多语种,泰语 / 泰语 / QA", tags: ["有声阅读","视频配音","多语种","泰语","QA","情感变化、指令遵循"] },
    { value: "tl_female_annika_uranus_bigtts", label: "Annika", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,菲律宾语 / 菲律宾语 / QA", tags: ["通用场景","视频配音","多语种","菲律宾语","QA","情感变化、指令遵循"] },
    { value: "tl_male_ed_uranus_bigtts", label: "Ed", gender: "male", age: "adult", tone: "通用场景, 视频配音,多语种,菲律宾语 / 菲律宾语 / QA", tags: ["通用场景","视频配音","多语种","菲律宾语","QA","情感变化、指令遵循"] },
    { value: "tl_female_hervie_uranus_bigtts", label: "Hervie", gender: "female", age: "adult", tone: "有声阅读, 视频配音, 客服���景,多语种,菲律宾语 / 菲律宾语 / QA", tags: ["有声阅读","视频配音","客服���景","多语种","菲律宾语","QA"] },
    { value: "vi_female_hong_uranus_bigtts", label: "Hong", gender: "female", age: "adult", tone: "通用场景, 客服场景,多语种,越南语 / 越南语 / QA", tags: ["通用场景","客服场景","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "vi_female_ling_uranus_bigtts", label: "Ling", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,越南语 / 越南语 / QA", tags: ["通用场景","视频配音","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "vi_female_linh_uranus_bigtts", label: "Linh", gender: "female", age: "adult", tone: "视频配音,多语种,越南语 / 越南语 / QA", tags: ["视频配音","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "vi_female_partner_uranus_bigtts", label: "Partner", gender: "female", age: "adult", tone: "视频配音, 客服场景,多语种,越南语 / 越南语 / QA", tags: ["视频配音","客服场景","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "vi_female_ruan_uranus_bigtts", label: "Ruan", gender: "female", age: "adult", tone: "通用场景,有声阅读, 角色扮演,多语种,越南语 / 越南语 / QA", tags: ["通用场景","有声阅读","角色扮演","多语种","越南语","QA"] },
    { value: "vi_female_wu_uranus_bigtts", label: "Wu", gender: "female", age: "adult", tone: "通用场景, 视频配音,多语种,越南语 / 越南语 / QA", tags: ["通用场景","视频配音","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "vi_male_wumg_uranus_bigtts", label: "Wumg", gender: "male", age: "adult", tone: "通用场景, 客服场景,多语种,越南语 / 越南语 / QA", tags: ["通用场景","客服场景","多语种","越南语","QA","情感变化、指令遵循"] },
    { value: "it_male_enzo_uranus_bigtts", label: "Enzo", gender: "male", age: "adult", tone: "通用场景, 教学场景,多语种,意大利语 / 意大利语 / Context", tags: ["通用场景","教学场景","多语种","意大利语","Context","情感变化、上下文遵循"] },
    { value: "zh_female_vv_jupiter_bigtts", label: "vivi", gender: "female", age: "adult", tone: "S2S-Omni / 中文", tags: ["S2S-Omni","中文"] },
    { value: "zh_female_xiaohe_jupiter_bigtts", label: "小何", gender: "female", age: "young", tone: "\"端到端实时语音大模型 S2S-O版本和SC-2.0版本 \"音色列表 / 中文", tags: ["\"端到端实时语音大模型","S2S-O版本和SC-2.0版本","\"音色列表","中文"] },
    { value: "zh_male_yunzhou_jupiter_bigtts", label: "云舟", gender: "male", age: "adult", tone: "\"端到端实时语音大模型 S2S-O版本和SC-2.0版本 \"音色列表 / 中文", tags: ["\"端到端实时语音大模型","S2S-O版本和SC-2.0版本","\"音色列表","中文"] },
    { value: "zh_male_xiaotian_jupiter_bigtts", label: "小天", gender: "male", age: "young", tone: "\"端到端实时语音大模型 S2S-O版本和SC-2.0版本 \"音色列表 / 中文", tags: ["\"端到端实时语音大模型","S2S-O版本和SC-2.0版本","\"音色列表","中文"] },
    { value: "zh_male_lengkugege_emo_v2_mars_bigtts", label: "冷酷哥哥（多情感）", gender: "male", age: "young", tone: "多情感 / 中文 / 生气、冷漠、恐惧、开心、厌恶、中性、悲伤、沮丧", tags: ["多情感","中文","生气、冷漠、恐惧、开心、厌恶、中性、悲伤、沮丧"] },
    { value: "zh_female_tianxinxiaomei_emo_v2_mars_bigtts", label: "甜心小美（多情感）", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文 / 悲伤、恐惧、厌恶、中性", tags: ["情感参数（emotion）：","中文","悲伤、恐惧、厌恶、中性","剪映同款"] },
    { value: "zh_female_gaolengyujie_emo_v2_mars_bigtts", label: "高冷御姐（多情感）", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文 / 开心、悲伤、生气、惊讶、恐惧、厌恶、激动、冷漠、中性", tags: ["情感参数（emotion）：","中文","开心、悲伤、生气、惊讶、恐惧、厌恶、激动、冷漠、中性","剪映同款"] },
    { value: "zh_male_aojiaobazong_emo_v2_mars_bigtts", label: "傲娇霸总（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 中性、开心、愤怒、厌恶", tags: ["情感参数（emotion）：","中文","中性、开心、愤怒、厌恶","剪映同款"] },
    { value: "zh_male_guangzhoudege_emo_mars_bigtts", label: "广州德哥（多情感）", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文 / 生气、恐惧、中性", tags: ["情感参数（emotion）：","中文","生气、恐惧、中性","剪映同款"] },
    { value: "zh_male_jingqiangkanye_emo_mars_bigtts", label: "京腔侃爷（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 开心、生气、惊讶、厌恶、中性", tags: ["情感参数（emotion）：","中文","开心、生气、惊讶、厌恶、中性","剪映同款"] },
    { value: "zh_female_linjuayi_emo_v2_mars_bigtts", label: "邻居阿姨（多情感）", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文 / 中性、愤怒、冷漠、沮丧、惊讶", tags: ["情感参数（emotion）：","中文","中性、愤怒、冷漠、沮丧、惊讶","剪映同款"] },
    { value: "zh_male_yourougongzi_emo_v2_mars_bigtts", label: "优柔公子（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 开心、生气、恐惧、厌恶、激动、中性、沮丧", tags: ["情感参数（emotion）：","中文","开心、生气、恐惧、厌恶、激动、中性、沮丧","剪映同款"] },
    { value: "zh_male_ruyayichen_emo_v2_mars_bigtts", label: "儒雅男友（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 开心、悲伤、生气、恐惧、激动、冷漠、中性", tags: ["情感参数（emotion）：","中文","开心、悲伤、生气、恐惧、激动、冷漠、中性","剪映同款"] },
    { value: "zh_male_junlangnanyou_emo_v2_mars_bigtts", label: "俊朗男友（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 开心、悲伤、生气、惊讶、恐惧、中性", tags: ["情感参数（emotion）：","中文","开心、悲伤、生气、惊讶、恐惧、中性","剪映同款"] },
    { value: "zh_male_beijingxiaoye_emo_v2_mars_bigtts", label: "北京小爷（多情感）", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文 / 生气，惊讶，恐惧，激动，冷漠，中性", tags: ["情感参数（emotion）：","中文","生气，惊讶，恐惧，激动，冷漠，中性"] },
    { value: "zh_female_roumeinvyou_emo_v2_mars_bigtts", label: "柔美女友（多情感）", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文 / 开心，悲伤，生气，惊讶，恐惧，厌恶，激动，冷漠，中性", tags: ["情感参数（emotion）：","中文","开心，悲伤，生气，惊讶，恐惧，厌恶，激动，冷漠，中性"] },
    { value: "zh_male_yangguangqingnian_emo_v2_mars_bigtts", label: "阳光青年（多情感）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 开心，悲伤，生气，恐惧，激动，冷漠，中性", tags: ["情感参数（emotion）：","中文","开心，悲伤，生气，恐惧，激动，冷漠，中性"] },
    { value: "zh_female_meilinvyou_emo_v2_mars_bigtts", label: "魅力女友（多情感）", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文 / 悲伤，恐惧，中性", tags: ["情感参数（emotion）：","中文","悲伤，恐惧，中性"] },
    { value: "zh_female_shuangkuaisisi_emo_v2_mars_bigtts", label: "爽快思思（多情感）", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文,英式英语 / 开心，悲伤，生气，惊讶，激动，冷漠，中性", tags: ["情感参数（emotion）：","中文","英式英语","开心，悲伤，生气，惊讶，激动，冷漠，中性"] },
    { value: "en_female_candice_emo_v2_mars_bigtts", label: "Candice", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语 / 深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、温暖", tags: ["情感参数（emotion）：","美式英语","深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、温暖"] },
    { value: "en_female_skye_emo_v2_mars_bigtts", label: "Serena", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语 / 深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖", tags: ["情感参数（emotion）：","美式英语","深情、愤怒、ASMR、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖"] },
    { value: "en_male_glen_emo_v2_mars_bigtts", label: "Glen", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语 / 深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖", tags: ["情感参数（emotion）：","美式英语","深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖"] },
    { value: "en_male_sylus_emo_v2_mars_bigtts", label: "Sylus", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语 / 深情、愤怒、ASMR、权威、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖", tags: ["情感参数（emotion）：","美式英语","深情、愤怒、ASMR、权威、对话/闲聊、兴奋、愉悦、中性、悲伤、温暖"] },
    { value: "en_male_corey_emo_v2_mars_bigtts", label: "Corey", gender: "male", age: "adult", tone: "情感参数（emotion）： / 英式英语 / 愤怒、ASMR、权威、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖", tags: ["情感参数（emotion）：","英式英语","愤怒、ASMR、权威、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖"] },
    { value: "en_female_nadia_tips_emo_v2_mars_bigtts", label: "Nadia", gender: "female", age: "adult", tone: "情感参数（emotion）： / 英式英语 / 深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖", tags: ["情感参数（emotion）：","英式英语","深情、愤怒、ASMR、对话/闲聊、深情、兴奋、愉悦、中性、悲伤、温暖"] },
    { value: "zh_male_shenyeboke_emo_v2_mars_bigtts", label: "深夜播客", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文 / 惊讶、悲伤、中性、厌恶、开心、恐惧、激动、沮丧、冷漠、生气", tags: ["情感参数（emotion）：","中文","惊讶、悲伤、中性、厌恶、开心、恐惧、激动、沮丧、冷漠、生气","猫箱同款"] },
    { value: "zh_female_yingyujiaoyu_mars_bigtts", label: "Tina老师", gender: "female", age: "adult", tone: "教育场景 / 中文,英式英语", tags: ["教育场景","中文","英式英语"] },
    { value: "zh_female_vv_mars_bigtts", label: "Vivi", gender: "female", age: "adult", tone: "通用场景 / 中文", tags: ["通用场景","中文"] },
    { value: "zh_female_qinqienvsheng_moon_bigtts", label: "亲切女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_qingyiyuxuan_mars_bigtts", label: "阳光阿辰", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_xudong_conversation_wvae_bigtts", label: "快乐小东", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "en_male_jason_conversation_wvae_bigtts", label: "开朗学长", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_sophie_conversation_wvae_bigtts", label: "魅力苏菲", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_tianmeitaozi_mars_bigtts", label: "甜美桃子", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_qingxinnvsheng_mars_bigtts", label: "清新女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_zhixingnvsheng_mars_bigtts", label: "知性女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_qingshuangnanda_mars_bigtts", label: "清爽男大", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_linjianvhai_moon_bigtts", label: "邻家女孩", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_yuanboxiaoshu_moon_bigtts", label: "渊博小叔", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款、剪映同款"] },
    { value: "zh_male_yangguangqingnian_moon_bigtts", label: "阳光青年", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_tianmeixiaoyuan_moon_bigtts", label: "甜美小源", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_qingchezizi_moon_bigtts", label: "清澈梓梓", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_jieshuoxiaoming_moon_bigtts", label: "解说小明", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_kailangjiejie_moon_bigtts", label: "开朗姐姐", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_linjiananhai_moon_bigtts", label: "邻家男孩", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_tianmeiyueyue_moon_bigtts", label: "甜美悦悦", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_xinlingjitang_moon_bigtts", label: "心灵鸡汤", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_wenrouxiaoge_mars_bigtts", label: "温柔小哥", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_cancan_mars_bigtts", label: "灿灿/Shiny", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语"] },
    { value: "zh_female_shuangkuaisisi_moon_bigtts", label: "爽快思思/Skye", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语","豆包同款"] },
    { value: "zh_male_wennuanahu_moon_bigtts", label: "温暖阿虎/Alvin", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语","豆包同款"] },
    { value: "zh_male_shaonianzixin_moon_bigtts", label: "少年梓辛/Brayan", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语","豆包同款、剪映同款"] },
    { value: "zh_male_hupunan_mars_bigtts", label: "沪普男", gender: "male", age: "adult", tone: "IP仿音 / 仅中文", tags: ["IP仿音","仅中文","豆包同款"] },
    { value: "zh_male_lubanqihao_mars_bigtts", label: "鲁班七号", gender: "male", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_female_yangmi_mars_bigtts", label: "林潇", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_female_linzhiling_mars_bigtts", label: "玲玲姐姐", gender: "female", age: "adult", tone: "情感参数（emotion）： / ���中文", tags: ["情感参数（emotion）：","���中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_female_jiyejizi2_mars_bigtts", label: "春日部姐姐", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_male_tangseng_mars_bigtts", label: "唐僧", gender: "male", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","抖音同款、豆包同款"] },
    { value: "zh_male_zhuangzhou_mars_bigtts", label: "庄周", gender: "male", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款"] },
    { value: "zh_male_zhubajie_mars_bigtts", label: "猪八戒", gender: "male", age: "young", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、豆包同款"] },
    { value: "zh_female_ganmaodianyin_mars_bigtts", label: "感冒电音姐姐", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款"] },
    { value: "zh_female_naying_mars_bigtts", label: "直率英子", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_female_leidian_mars_bigtts", label: "女雷神", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、豆包同款"] },
    { value: "zh_female_yueyunv_mars_bigtts", label: "粤语小溏", gender: "female", age: "adult", tone: "趣味口音 / 中文", tags: ["趣味口音","中文"] },
    { value: "zh_male_yuzhouzixuan_moon_bigtts", label: "豫州子轩", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文-河南口音", tags: ["情感参数（emotion）：","中文-河南口音","豆包同款"] },
    { value: "zh_female_daimengchuanmei_moon_bigtts", label: "呆萌川妹", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文-四川口音", tags: ["情感参数（emotion）：","中文-四川口音","豆包同款"] },
    { value: "zh_male_guangxiyuanzhou_moon_bigtts", label: "广西远舟", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文-广西口音", tags: ["情感参数（emotion）：","中文-广西口音","豆包同款"] },
    { value: "zh_male_zhoujielun_emo_v2_mars_bigtts", label: "双节棍小哥", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文-台湾口音", tags: ["情感参数（emotion）：","中文-台湾口音","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_female_wanwanxiaohe_moon_bigtts", label: "湾湾小何", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文-台湾口音", tags: ["情感参数（emotion）：","中文-台湾口音","豆包同款"] },
    { value: "zh_female_wanqudashu_moon_bigtts", label: "湾区大叔", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文-广东口音", tags: ["情感参数（emotion）：","中文-广东口音","豆包同款"] },
    { value: "zh_male_guozhoudege_moon_bigtts", label: "广州德哥", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文-广东口音", tags: ["情感参数（emotion）：","中文-广东口音","豆包同款"] },
    { value: "zh_male_haoyuxiaoge_moon_bigtts", label: "浩宇小哥", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文-青岛口音", tags: ["情感参数（emotion）：","中文-青岛口音","豆包同款"] },
    { value: "zh_male_beijingxiaoye_moon_bigtts", label: "北京小爷", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文-北京口音", tags: ["情感参数（emotion）：","中文-北京口音","豆包同款"] },
    { value: "zh_male_jingqiangkanye_moon_bigtts", label: "京腔侃爷/Harmony", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文-北京口音,美式英语", tags: ["情感参数（emotion）：","中文-北京口音","美式英语","豆包同款"] },
    { value: "zh_female_meituojieer_moon_bigtts", label: "妹坨洁儿", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文-长沙口音", tags: ["情感参数（emotion）：","中文-长沙口音","豆包同款、剪映同款"] },
    { value: "zh_male_naiqimengwa_mars_bigtts", label: "奶气萌娃", gender: "male", age: "young", tone: "角色扮演 / 中文", tags: ["角色扮演","中文","剪映同款、豆包同款"] },
    { value: "zh_female_popo_mars_bigtts", label: "婆婆", gender: "female", age: "old", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_female_gaolengyujie_moon_bigtts", label: "高冷御姐", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_aojiaobazong_moon_bigtts", label: "傲娇霸总", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_meilinvyou_moon_bigtts", label: "魅力女友", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款、剪映同款"] },
    { value: "zh_male_shenyeboke_moon_bigtts", label: "深夜播客", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_sajiaonvyou_moon_bigtts", label: "柔美女友", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款、剪映同款"] },
    { value: "zh_female_yuanqinvyou_moon_bigtts", label: "撒娇学妹", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款、剪映同款"] },
    { value: "zh_male_dongfanghaoran_moon_bigtts", label: "东方浩然", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_jiaochuan_mars_bigtts", label: "娇喘女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款"] },
    { value: "zh_male_livelybro_mars_bigtts", label: "开朗弟弟", gender: "male", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款"] },
    { value: "zh_female_flattery_mars_bigtts", label: "谄媚女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 仅中文", tags: ["情感参数（emotion）：","仅中文","剪映同款、抖音同款"] },
    { value: "en_female_lauren_moon_bigtts", label: "Lauren", gender: "female", age: "adult", tone: "多语种 / 美式英语", tags: ["多语种","美式英语"] },
    { value: "en_male_campaign_jamal_moon_bigtts", label: "EnergeticMaleII", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_male_chris_moon_bigtts", label: "GothamHero", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_female_product_darcie_moon_bigtts", label: "FlirtyFemale", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_female_emotional_moon_bigtts", label: "PeacefulFemale", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_female_nara_moon_bigtts", label: "Nara", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_male_bruce_moon_bigtts", label: "Bruce", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "zh_male_M100_conversation_wvae_bigtts", label: "Lucas", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语","豆包同款"] },
    { value: "en_female_dacey_conversation_wvae_bigtts", label: "Daisy", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语","豆包同款"] },
    { value: "en_male_charlie_conversation_wvae_bigtts", label: "Owen", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语","豆包同款"] },
    { value: "en_female_sarah_new_conversation_wvae_bigtts", label: "Luna", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语","豆包同款"] },
    { value: "en_male_adam_mars_bigtts", label: "Adam", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_female_amanda_mars_bigtts", label: "Amanda", gender: "female", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_male_jackson_mars_bigtts", label: "Jackson", gender: "male", age: "adult", tone: "情感参数（emotion）： / 美式英语", tags: ["情感参数（emotion）：","美式英语"] },
    { value: "en_female_daisy_moon_bigtts", label: "DelicateGirl", gender: "female", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_male_dave_moon_bigtts", label: "Dave", gender: "male", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_male_hades_moon_bigtts", label: "Hades", gender: "male", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_female_onez_moon_bigtts", label: "Onez", gender: "female", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_female_emily_mars_bigtts", label: "Emily", gender: "female", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语","豆包同款"] },
    { value: "en_male_smith_mars_bigtts", label: "Smith", gender: "male", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_female_anna_mars_bigtts", label: "Anna", gender: "female", age: "adult", tone: "情感参数（emotion）： / 英式英语", tags: ["情感参数（emotion）：","英式英语"] },
    { value: "en_female_sarah_mars_bigtts", label: "Sarah", gender: "female", age: "adult", tone: "情感参数（emotion）： / 澳洲英语", tags: ["情感参数（emotion）：","澳洲英语"] },
    { value: "en_male_dryw_mars_bigtts", label: "Dryw", gender: "male", age: "adult", tone: "情感参数（emotion）： / 澳洲英语", tags: ["情感参数（emotion）：","澳洲英语"] },
    { value: "multi_female_maomao_conversation_wvae_bigtts", label: "Diana", gender: "female", age: "adult", tone: "情感参数（emotion）： / 西语", tags: ["情感参数（emotion）：","西语"] },
    { value: "multi_male_M100_conversation_wvae_bigtts", label: "Lucía", gender: "male", age: "adult", tone: "情感参数（emotion）： / 西语", tags: ["情感参数（emotion）：","西语"] },
    { value: "multi_female_sophie_conversation_wvae_bigtts", label: "Sofía", gender: "female", age: "adult", tone: "情感参数（emotion）： / 西语", tags: ["情感参数（emotion）：","西语"] },
    { value: "multi_male_xudong_conversation_wvae_bigtts", label: "Daníel", gender: "male", age: "adult", tone: "情感参数（emotion）： / 西语", tags: ["情感参数（emotion）：","西语"] },
    { value: "multi_zh_male_youyoujunzi_moon_bigtts", label: "ひかる（光）", gender: "male", age: "adult", tone: "情感参数（emotion）： / 日语", tags: ["情感参数（emotion）：","日语"] },
    { value: "multi_female_gaolengyujie_moon_bigtts", label: "あけみ（朱美）", gender: "female", age: "young", tone: "情感参数（emotion）： / 日语", tags: ["情感参数（emotion）：","日语"] },
    { value: "multi_male_jingqiangkanye_moon_bigtts", label: "かずね（和音）/JavierorÁlvaro", gender: "male", age: "adult", tone: "情感参数（emotion）： / 日语,西语", tags: ["情感参数（emotion）：","日语","西语"] },
    { value: "multi_female_shuangkuaisisi_moon_bigtts", label: "はるこ（晴子）/Esmeralda", gender: "female", age: "adult", tone: "情感参数（emotion）： / 日语,西语", tags: ["情感参数（emotion）：","日语","西语"] },
    { value: "multi_male_wanqudashu_moon_bigtts", label: "ひろし（広志）/Roberto", gender: "male", age: "adult", tone: "情感参数（emotion）： / 日语,西语", tags: ["情感参数（emotion）：","日语","西语"] },
    { value: "zh_female_kefunvsheng_mars_bigtts", label: "暖阳女声", gender: "female", age: "adult", tone: "客服场景 / 仅中文", tags: ["客服场景","仅中文"] },
    { value: "zh_female_maomao_conversation_wvae_bigtts", label: "文静毛毛", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_female_wenrouxiaoya_moon_bigtts", label: "温柔小雅", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","豆包同款"] },
    { value: "zh_male_tiancaitongsheng_mars_bigtts", label: "天才童声", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_sunwukong_mars_bigtts", label: "猴哥", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_xionger_mars_bigtts", label: "熊二", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_female_peiqi_mars_bigtts", label: "佩奇猪", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_female_wuzetian_mars_bigtts", label: "武则天", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","剪映同款"] },
    { value: "zh_female_gujie_mars_bigtts", label: "顾姐", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","抖音同款、剪映同款"] },
    { value: "zh_female_yingtaowanzi_mars_bigtts", label: "樱桃丸子", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_male_chunhui_mars_bigtts", label: "广告解说", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","剪映同款"] },
    { value: "zh_female_shaoergushi_mars_bigtts", label: "少儿故事", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_silang_mars_bigtts", label: "四郎", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","抖音同款、剪映同款、豆包同款"] },
    { value: "zh_female_qiaopinvsheng_mars_bigtts", label: "俏皮女声", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_lanxiaoyang_mars_bigtts", label: "懒音绵宝", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_dongmanhaimian_mars_bigtts", label: "亮嗓萌仔", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_male_jieshuonansheng_mars_bigtts", label: "磁性解说男声/Morgan", gender: "male", age: "young", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语","抖音同款、剪映同款"] },
    { value: "zh_female_jitangmeimei_mars_bigtts", label: "鸡汤妹妹/Hope", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语","抖音同款、豆包同款"] },
    { value: "zh_female_tiexinnvsheng_mars_bigtts", label: "贴心女声/Candy", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语"] },
    { value: "zh_female_mengyatou_mars_bigtts", label: "萌丫头/Cutey", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文,美式英语", tags: ["情感参数（emotion）：","中文","美式英语"] },
    { value: "zh_male_changtianyi_mars_bigtts", label: "悬疑解说", gender: "male", age: "adult", tone: "有声阅读 / 中文", tags: ["有声阅读","中文","剪映同款、抖音同款、豆包同款"] },
    { value: "zh_male_ruyaqingnian_mars_bigtts", label: "儒雅青年", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","番茄小说同款、豆包同款、剪映同款"] },
    { value: "zh_male_baqiqingshu_mars_bigtts", label: "霸气青叔", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","番茄小说同款、豆包同款、剪映同款"] },
    { value: "zh_male_qingcang_mars_bigtts", label: "擎苍", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","番茄小说同款、剪映同款、豆包同款、抖音同款"] },
    { value: "zh_male_yangguangqingnian_mars_bigtts", label: "活力小哥", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_gufengshaoyu_mars_bigtts", label: "古风少御", gender: "female", age: "young", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
    { value: "zh_female_wenroushunv_mars_bigtts", label: "温柔淑女", gender: "female", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文","番茄小说同款、豆包同款、剪映同款"] },
    { value: "zh_male_fanjuanqingnian_mars_bigtts", label: "反卷青年", gender: "male", age: "adult", tone: "情感参数（emotion）： / 中文", tags: ["情感参数（emotion）：","中文"] },
] satisfies VolcengineVoiceOption[];
